repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
        exclude: ^tests/doctools/output/
      - id: end-of-file-fixer
        exclude: ^tests/doctools/output/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      language_version: python3.7
      exclude: __init__.py
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.1
    hooks:
    - id: isort
      additional_dependencies: [toml]
