# {% set data = load_setup_py_data() %}
# {% set version = 0.10.0rc0%}

package:
  name: footings
  version: # {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm

  run:
    - attrs>=20.0.0
    - numpy>=1.11.0
    - pandas>=1.0.*
    - numpydoc=1.0.*
    - openpyxl

test:
  imports:
    - footings

about:
  home: # {{ data['url'] }}
  license: # {{ data['license'] }}
summary: # {{ data['description'] }}
