name: Publish Release

on:
  push:
    tags: ["v*"]

jobs:
  build-n-publish:
    name: Build and publish package to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pipx
      run: |
        python3 -m pip install pipx
    - name: Install poetry
      run: |
        pipx install poetry
    - name: Configure pypi credentials
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: poetry config http-basic.pypi __token__ "$PYPI_API_TOKEN"
    - name: Publish release to pypi
      run: poetry publish --build
